name: 'Update CloudFront Origin'
description: 'Updates the CloudFront Origin and invalidates the cache'
inputs:
  distributions:
    description: JSON map of origins mapped to release branch
    required: true
    default: '{}'
  originId:
    description: The Origin ID to replace
    required: false
    default: S3-spear-static-sites
  projectKey:
    description: The Project Key, used to build the spear-static-sites path
    required: false
runs:
  using: 'node16'
  main: 'index.js'
